export const GET_TOP_MOVIES_API_REQUEST = 'GET_TOP_MOVIES_API_REQUEST';
export const GET_TOP_MOVIES_API_SUCCESS = 'GET_TOP_MOVIES_API_SUCCESS';
export const GET_TOP_MOVIES_API_FAILURE = 'GET_TOP_MOVIES_API_FAILURE';

export const GET_MOVIE_DETAILS_API_REQUEST = 'GET_MOVIE_DETAILS_API_REQUEST';
export const GET_MOVIE_DETAILS_API_SUCCESS = 'GET_MOVIE_DETAILS_API_SUCCESS';
export const GET_MOVIE_DETAILS_API_FAILURE = 'GET_MOVIE_DETAILS_API_FAILURE';

export const SEARCH_MOVIE_API_REQUEST = 'SEARCH_MOVIE_API_REQUEST';
export const SEARCH_MOVIE_API_SUCCESS = 'SEARCH_MOVIE_API_SUCCESS';
export const SEARCH_MOVIE_API_FAILURE = 'SEARCH_MOVIE_API_FAILURE';